name: Grading workflow
on: 
  push:
    paths:
    - '.github/workflows/stale-*.yml'
  workflow_dispatch:

jobs:
  grade-learner:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade scheduled events activity
        id: events
        uses: ./.github/actions/yaml-parser-action
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          files: "stale-weekly.yml"
      - name: Troubleshooting info for grading
        uses: githubtraining/looking-glass-action@507f3d308fd92b17b44dfdedd458a5c8854459c4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feedback: ${{ steps.events.outputs.reports }}
  troubleshoot-activity:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "To get started, change the on field in stale-weekly.yml."
